### PR TITLE
Missing spacing on the reject confirmation prompt

### PR DESCRIPTION
**Pull request by Pitu**
Looks odd that there's no spacing between the options, this should take care of it.

### CODE REVIEW

**Comment by zajrik** [comment]
I wouldn't call this missing spacing. It was a deliberate design choice to save horizontal space and is present in every other prompt given from other commands as well. If you're going to change one it'd be best to change them all.

Off the top of my head this includes the reject command, config command under the reset option, history command under the reset option and the clearlogs command. Possibly others but I'm on mobile right now and don't have the free time to dig 'em up until several hours from now.

**Comment by Pitu** [comment]
Oh, I called it missing spacing just because I noticed that when trying to ban someone, that spacing is actually present.
`Are you sure you want to issue this ban? (yes | no)`
That's the reason I initially thought this was an oversight on the reject prompt, but if you're telling me it's not and you agree to add them, I can dig up every prompt and modify my pr to include them all.

**Comment by zajrik** [comment]
You're correct, actually. I was mistaken on this. I really thought I had left the spaces out on all of them but it turns out I had just done it on this one. Honestly I should have saved reviewing this until I wasn't quite so tired. It does look better with the spaces so this is fine. Thanks for changing it. 👌

**Comment by Pitu** [comment]
Glad to help!

**Comment by zajrik** [comment]
Not sure when I'll be pulling stable down next but I'll go ahead and comment here when the change goes live.

**Pull request merged**
